SDL_PROC(EGLDisplay, eglGetDisplay, (NativeDisplayType display));
SDL_PROC(EGLDisplay, eglGetPlatformDisplayEXT, (EGLenum platform, void *native_display, const EGLint *attrib_list));
SDL_PROC(EGLBoolean, eglInitialize, (EGLDisplay dpy, EGLint * major, EGLint * minor));
SDL_PROC(EGLBoolean, eglTerminate, (EGLDisplay dpy));
SDL_PROC(void *, eglGetProcAddress, (const char * procName));
SDL_PROC(EGLBoolean, eglGetConfigs, (EGLDisplay dpy, EGLConfig * configs, EGLint config_size, EGLint * num_config));
SDL_PROC(EGLBoolean, eglChooseConfig, (EGLDisplay dpy, const EGLint * attrib_list, EGLConfig * configs, EGLint config_size, EGLint * num_config));
SDL_PROC(EGLContext, eglCreateContext, (EGLDisplay dpy, EGLConfig config, EGLContext share_list, const EGLint * attrib_list));
SDL_PROC(EGLBoolean, eglDestroyContext, (EGLDisplay dpy, EGLContext ctx));
SDL_PROC(EGLImageKHR, eglCreateImageKHR, (EGLDisplay display, EGLContext context, EGLenum target, EGLClientBuffer buffer, const EGLint *attrib_list));
SDL_PROC(EGLBoolean, eglDestroyImageKHR, (EGLDisplay dpy, EGLImageKHR image));
SDL_PROC(EGLSurface, eglCreatePixmapSurface, (EGLDisplay dpy, EGLConfig config, NativePixmapType pixmap, const EGLint * attrib_list));
SDL_PROC(EGLSurface, eglCreatePbufferSurface, (EGLDisplay dpy, EGLConfig config, EGLint const* attrib_list));
SDL_PROC(EGLSurface, eglCreateWindowSurface, (EGLDisplay dpy, EGLConfig config, NativeWindowType window, const EGLint * attrib_list));
SDL_PROC(EGLBoolean, eglDestroySurface, (EGLDisplay dpy, EGLSurface surface));
SDL_PROC(EGLBoolean, eglMakeCurrent, (EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx));
SDL_PROC(EGLBoolean, eglSwapBuffers, (EGLDisplay dpy, EGLSurface draw));
SDL_PROC(EGLBoolean, eglSwapInterval, (EGLDisplay dpy, EGLint interval));
SDL_PROC(const char *, eglQueryString, (EGLDisplay dpy, EGLint name));
SDL_PROC(EGLenum, eglQueryAPI, (void));
SDL_PROC(EGLBoolean, eglGetConfigAttrib, (EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint * value));
SDL_PROC(EGLBoolean, eglWaitNative, (EGLint  engine));
SDL_PROC(EGLBoolean, eglWaitGL, (void));
SDL_PROC(EGLBoolean, eglReleaseThread, (void));
SDL_PROC(EGLBoolean, eglBindAPI, (EGLenum));
SDL_PROC(EGLint, eglGetError, (void));
SDL_PROC(EGLSyncKHR, eglCreateSyncKHR, (EGLDisplay dpy, EGLenum type, const EGLint *attrib_list));
SDL_PROC(EGLBoolean, eglDestroySyncKHR, (EGLDisplay dpy, EGLSyncKHR sync));
//SDL_PROC(EGLint, eglWaitSyncKHR, (EGLDisplay dpy, EGLSyncKHR sync, EGLint flags));
SDL_PROC(EGLint, eglClientWaitSyncKHR, (EGLDisplay dpy, EGLSyncKHR sync, EGLint flags, EGLTimeKHR timeout));
